---
title: "Proyecto de Curso - William Coronado Lou"
output: html_notebook
---

1. Conociendo los datos

```{r}
library(dplyr)

#1.1. Cargue el paquete tidyverse.
library(tidyverse)

#1.2. Lea el archivo deaths_handwashing.csv usando read_csv y asígnelo a la variable yearly.
yearly <- read_csv("deaths_handwashing.csv")

#1.3. Imprima la variable yearly
yearly

summary(yearly)
```

2. El alarmante número de muertes

```{r}
#2.1. Use mutate para agregar la columna proportion_deaths a yearly, esta nueva columna se
#calculará como la proporción de muertes por número de nacimientos.

yearly <- mutate(yearly, proportion_deaths = round(deaths/births,4))


#2.2. Imprima yearly.

yearly

```


3. Muerte en las clínicas
```{r}
library(ggplot2)
#3.1. Utilice ggplot para hacer una gráfica lineal de proportion_deaths por año (columna year) con una línea por clínica.
#3.2. Las líneas deben tener colores distintos.


ggplot(data=yearly, aes(x=year, y=proportion_deaths, group=clinic, colour = clinic)) +
  geom_line()+
  geom_point() +
  labs(title = "Proportion of deaths [quantity of deaths/quantity of births] by clinic", y="Proportion of deaths", x="Year")


```
Análisis preliminar: es notable una diferencia entre la proporción de muertes de la clínica 1 y la clínica 2. Es más alta en la clínica 1.

4. Comienza el lavado de manos
```{r}

#4.1. Cargue los datos mensuales de la Clínica 1 para ver si el lavado de manos tuvo algún
#efecto, para esto lea el archivo deaths_clinic_1.csv y asígnelo a la variable monthly.

monthly <- read_csv("deaths_clinic_1.csv")


monthly
summary(monthly)


#4.2. Agregue la columna proportion_deaths a monthly, esta nueva columna se calculará
#como la proporción de muertes por número de nacimientos.

monthly <- mutate(monthly, proportion_deaths = round(deaths/births,4))
monthly

#4.3. Imprima las primeras filas de monthly usando la función head().

head(monthly)




```




5.El efecto del lavado de manos

```{r}
#5.1. Haga una gráfica lineal de proportion_deaths por fecha para el data frame monthly usando ggplot.
# 5.2. Utilice la función labs para dar al eje x y al eje y una estética a las etiquetas.

ggplot(data=monthly, aes(x=date, y=proportion_deaths,)) +
  geom_line()+
  geom_point() +
  labs(title = "Daily Proportion of deaths [quantity of deaths/quantity of births] in Clinic 1", y="Proportion of deaths", x="Date")

```



6. Los resultados del lavado de manos

```{r}
#6.1. Agregue una columna TRUE/FALSE a monthly llamado handwashing_started, que será
#TRUE a partir del año en que se impuso el lavado de manos.

monthly_handwashing_started_df <- monthly %>%
mutate(monthly, handwashing_started = ifelse(date >= "1847-01-01" , TRUE, FALSE))
monthly_handwashing_started_df

#6.2. Haga una gráfica lineal de proportion_deaths por fecha para el data frame monthly
#usando ggplot. Haga que el color de la línea dependa de handwashing_started.
#6.3. Utilice la función labs para dar al eje x y al eje y una estética a las etiquetas.

ggplot(data=monthly_handwashing_started_df, aes(x=date, y=proportion_deaths, group=handwashing_started, colour = handwashing_started)) +
  geom_line()+
  geom_point() +
  labs(title = "Proportion of deaths [quantity of deaths/quantity of births] on clinic 1", y="Proportion of deaths", x="Date")


```

7. ¿Más lavado de manos, menos muertes?

```{r}

#7.1. Utilice group_by y summarise para calcular el promedio de proportion_deaths antes y
#después de que se impusiera el lavado de manos.

month_summary <- monthly_handwashing_started_df %>% 
  group_by(handwashing_started)  %>%
  summarise(mean(proportion_deaths))
  
  
month_summary


#7.2. Asigne el resultado en la variable month_summary e imprímala.

#7.3. El data frame resultante debería verse como el siguiente:

```

